ALTER PROFILE LYC LIMIT
  SESSIONS_PER_USER UNLIMITED
  CPU_PER_SESSION DEFAULT
  CPU_PER_CALL DEFAULT
  CONNECT_TIME UNLIMITED
  IDLE_TIME UNLIMITED
  LOGICAL_READS_PER_SESSION DEFAULT
  LOGICAL_READS_PER_CALL DEFAULT
  COMPOSITE_LIMIT DEFAULT
  PRIVATE_SGA DEFAULT
  FAILED_LOGIN_ATTEMPTS Unlimited
  PASSWORD_LIFE_TIME Unlimited
  PASSWORD_REUSE_TIME Unlimited
  PASSWORD_REUSE_MAX Unlimited
  PASSWORD_LOCK_TIME 0.0415
  PASSWORD_GRACE_TIME Unlimited
  PASSWORD_VERIFY_FUNCTION NULL;

select 'alter user '||username||' identified by values '''||password||''';' from dba_users where username like 'U%' or username like 'N%'

ALTER PROFILE LYC LIMIT
  SESSIONS_PER_USER UNLIMITED
  CPU_PER_SESSION DEFAULT
  CPU_PER_CALL DEFAULT
  CONNECT_TIME UNLIMITED
  IDLE_TIME UNLIMITED
  LOGICAL_READS_PER_SESSION DEFAULT
  LOGICAL_READS_PER_CALL DEFAULT
  COMPOSITE_LIMIT DEFAULT
  PRIVATE_SGA DEFAULT
  FAILED_LOGIN_ATTEMPTS 6
  PASSWORD_LIFE_TIME 90
  PASSWORD_REUSE_TIME 180
  PASSWORD_REUSE_MAX 5
  PASSWORD_LOCK_TIME 0.0415
  PASSWORD_GRACE_TIME 7
  PASSWORD_VERIFY_FUNCTION VERIFY_FUNCTION_BYDBA;
